### ISSUE TITLE
Explain how to install

### ISSUE THREAD

**Issue by ericandrewlewis** [krakjoe/explain#2]
I followed along with [this article](http://devzone.zend.com/303/extension-writing-part-i-introduction-to-php-and-zend/) to figure out how to get this working. This is the command from the explain project's root:

```
$ phpize; ./configure; make;
```

This will create `modules/explain.so`, which you can include in your php invocation to load the explain extension dynamically.

```
$ php -dextension=modules/explain.so explain.php ../path/to/php/for/analysis.php
```

**Comment by krakjoe** [comment]
`sudo make install`
